version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-local-development-secret
    volumes:
      - ./data:/data
    restart: unless-stopped